### PR TITLE
Adding AecGridsExtension

### PR DESCRIPTION
**Pull request by yiskang**
Rework of the `drawGrid` demo of this blog: [Consume AEC Data which are from Model Derivative API](https://forge.autodesk.com/blog/consume-aec-data-which-are-model-derivative-api). 

This version includes those improvements:

- Supports Viewer v7
- Fix [text alignment](https://stackoverflow.com/a/57571964) issue and remove dependencies of THREE.TextGeometry and THREE.Font.
- Fix grid placement issue.
- Create grids for each levels.

### CODE REVIEW

**Comment by libvarun** [comment]
I'm getting error on selecting floors, also on selecting a particular floor it's just make the elements white and selected in some cases, isn't it supposed to isolate and focus?
image

**Review by libvarun — COMMENTED** [review]
I'm getting error on selecting floors, also on selecting a particular floor it's just make the elements white and selected in some cases, isn't it supposed to isolate and focus?
image

**Comment by yiskang** [comment]
Hi Varun,

It’s from the viewer built-in extension, Viewport , not from this one. So I think we can ignore it.

However, I’m
trying to gather some information about this problem, and will report to viewer engineering team later.

**Comment by yiskang** [comment]
BTW, I noticed that the model you're trying doesn't have the grid data in its AEC Model Data.

[![enter image description here][1]][1]
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/Q5hMq.png
  [2]: https://i.stack.imgur.com/9IqCj.png

**Comment by libvarun** [comment]
> BTW, I noticed that the model you're trying doesn't have the grid data in its AEC Model Data.
> 
> [enter image description here](https://i.stack.imgur.com/Q5hMq.png)
> [enter image description here](https://i.stack.imgur.com/9IqCj.png)

ok, in that case, we should alert, saying this model doesn't contain the AEC model data?

**Comment by yiskang** [comment]
Yeah, I added a warning for that in the above commit.

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/ixS8P.png

**Comment by libvarun** [comment]
is that printed in console? I think it should be alerted, not everyone may have the console opened.
alert("This model doesn't contain **AEC Model Data**, unloading the extension..")

**Comment by libvarun** [comment]
Please give me a model to test.

**Comment by yiskang** [comment]
Ok, now it will alert and warn in the console for invalid data. 

Please use those Revit samples for testing from [AKN](https://knowledge.autodesk.com/support/revit-products/getting-started/caas/CloudHelp/cloudhelp/2020/ENU/Revit-GetStarted/files/GUID-61EF2F22-3A1F-4317-B925-1E85F138BE88-htm.html):

- http://www.autodesk.com/revit-rac-basic-sample-project-2020-enu
- http://www.autodesk.com/revit-rme-advanced-project-sample-2020-enu

**Comment by libvarun** [comment]
I was unable to download those 2, I used office king revit model, here's the screenshot, is this expected behavior?
I'm seeing lines and few round objects. other than that the old error is appearing which is not the extension fault as mentioned by you earlier.
image

**Comment by yiskang** [comment]
Yes, those lines and few round objects represent grids creating by this extension. if we applying some cut planes, it will look like this:
[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/xvCr3.jpg

About the model file, strange... try these two from [Revit 2021](https://knowledge.autodesk.com/support/revit-products/getting-started/caas/CloudHelp/cloudhelp/2021/ENU/Revit-GetStarted/files/GUID-61EF2F22-3A1F-4317-B925-1E85F138BE88-htm.html)

- http://www.autodesk.com/revit-rac-basic-sample-project-2021-enu
- http://www.autodesk.com/revit-rac-advanced-sample-project-2021-enu

**Comment by yiskang** [comment]
@libvarun I improved the failure handling logics based on @augustogoncalves and your suggestions.

**Comment by libvarun** [comment]
@yiskang it's good to go,  two minor things, AEC is repeated twice in the alert message. After unloading please uncheck the extension from the list.

**Comment by libvarun** [comment]
Also, please add a note in the readme that this extension works only with models containing AEC data and a bit explanation of how the extension works.

**Comment by yiskang** [comment]
Done!

- Fixed typo and README
- It will check/uncheck the extension checkbox if we call viewer API to load/unload the extension. I added some handlers in ForgeViewer.js

**Pull request merged**
